site_url: https://heiafr-isc.github.io/website-template/
site_name: Template for mkdocs website version Q3-2023
site_description: Template for mkdocs website
copyright: "Copyright &copy; {{ cal.today.year }} Haute école d'ingénierie et d'architecture of Fribourg"

repo_url: https://github.com/heiafr-isc/website-template
repo_name: heiafr-isc/website-template
edit_uri: https://github.com/heiafr-isc/website-template/edit/main/docs/

extra:
  show_page_revision_on_all_pages: false
  teacher_name: "Jacques Supcik"
  year: "2023-2024"

  lecture_week: !ENV [LECTURE_WEEK, "999"]
  lecture_week: !ENV [LECTURE_WEEK, "999"]
  exercice_week: !ENV [EXERCISE_WEEK, "999"]
  assignment_week: !ENV [ASSIGNMENT_WEEK, "999"]
  exercice_show_solution: !ENV [EXERCICE_SHOW_SOLUTION, "999"]
  assignment_show_solution: !ENV [ASSIGNMENT_SHOW_SOLUTION, "999"]
  exam_show_objectives: !ENV [EXAM_SHOW_OBJECTIVES, "999"]


  consent:
    title: Utilisation des cookie
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos
      préférences, ainsi que pour mesurer l'efficacité de notre documentation
      et déterminer si les utilisateurs trouvent ce qu'ils recherchent.
      Avec votre consentement, vous nous aidez à améliorer notre documentation.
  social:
    - icon: material/web
      link: https://www.heia-fr.ch/fr/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/heiafr.htafr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HEIAFR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/heiafr/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/heiafr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/eiafr

theme:
  name: material
  language: "fr"
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  custom_dir: "overrides/"
  icon:
    logo: material/school
  favicon: "assets/images/favicon.ico"
  features:
    - content.code.annotate
    - navigation.sections
    - content.code.copy

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  admonition: {}
  extra: {}
  smarty:
    smart_angled_quotes: true
    substitutions:
      left-angle-quote: "&laquo;&#xA0;"
      right-angle-quote: "&#xA0;&raquo;"
  mkdcomments: {}
  footnotes: {}
  codehilite: {}
  pymdownx.arithmatex:
    generic: true
  pymdownx.betterem:
    smart_enable: all
  pymdownx.tabbed: {}
  pymdownx.highlight: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.details: {}
  pymdownx.keys: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.inlinehilite: {}
  pymdownx.magiclink: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.superfences: {}
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.tilde: {}
  mdx_math: {}
  attr_list: {}
  md_in_html: {}

plugins:
  - search
  - calendar
  - jconfig:
      items:
        - copyright
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - awesome-pages
  - macros
  - pages-j2
