name: publish-websites

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"

# Change the following for conditional deployment
env:
  LECTURE_SHOW: 2
  EXAM_SHOW_OBJECTIVES: 999
  EXERCISE_SHOW_DATA: 2
  EXERCISE_SHOW_SOLUTION: 1
  ASSIGNMENT_SHOW_DATA: 2
  ASSIGNMENT_SHOW_SOLUTION: 1

jobs:
  # Build site
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build mkdocs site
        uses: ./.github/actions/mkdocs-edu

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  # Deploy site to Github pages
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates
                        # from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
